{{- if and .Values.ingress.enabled .Values.ingress.tls.autoTLS (not .Values.ingress.tls.secretName) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "helm-chart.default-ingress-tls-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewall.labels" . | nindent 4 }}
    app: {{ include "helm-chart.default-ingress-tls-secret-name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{ ( include "helm-chart.gen-ingress-certs" . ) | indent 2 }}
{{- end }}
